//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A4
    {

        public virtual Concert Concert { get; set; }
        public virtual Leader Leader { get; set; }
    }
}
