//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Concert> Concerts { get; set; }
        public virtual DbSet<Stringer> Stringers { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<Picture> Pics { get; set; }
        public virtual DbSet<Leader> Leaders { get; set; }
        public virtual DbSet<A1> A1 { get; set; }
        public virtual DbSet<A2> A2 { get; set; }
        public virtual DbSet<A3> A3 { get; set; }
        public virtual DbSet<A4> A4 { get; set; }
        public virtual DbSet<Composer> Composers { get; set; }
        public virtual DbSet<Genus> Genus { get; set; }
        public virtual DbSet<Adverties> Adverties { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<File> Files { get; set; }
    }
}
