//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symphony.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.A2 = new HashSet<A2>();
            this.A3 = new HashSet<A3>();
        }
    
    
        public virtual Composer Composer { get; set; }
        public virtual ICollection<A2> A2 { get; set; }
        public virtual ICollection<A3> A3 { get; set; }
    }
}
